import productImage from './assets/images/img1.png'
export const products = [
  {
    _id: '1',
    name: 'English Navy',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 999,
    discount: 52,
    isNew: true,
  },
  {
    _id: '2',
    name: 'English Navy 2',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 800,
    discount: 21,
    isNew: true,
  },
  {
    _id: '3',
    name: 'English Navy 3',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 700,
    discount: 52,
    isNew: false,
  },
  {
    _id: '4',
    name: 'English Navy 4',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 999,
    discount: 52,
    isNew: true,
  },
  {
    _id: '5',
    name: 'English Navy 5',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 1200,
    discount: 12,
    isNew: false,
  },
  {
    _id: '6',
    name: 'English Navy 6',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 999,
    discount: 52,
    isNew: true,
  },
  {
    _id: '7',
    name: 'English Navy 7',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 999,
    discount: 52,
    isNew: true,
  },
  {
    _id: '8',
    name: 'English Navy 8',
    subHeading: ' Men Slim Fit Formal Shirt',
    url: productImage,
    price: 1899,
    discount: 77,
    isNew: false,
  },
]
